
# TODO: what about directionality?
emotions = [
    # Labels from google-research-datasets/go_emotions, minus "neutral"
    "admiration",
    "amusement",
    "anger",
    "annoyance",
    "approval",
    "caring",
    "confusion",
    "curiosity",
    "desire",
    "disappointment",
    "disapproval",
    "disgust",
    "embarrassment",
    "excitement",
    "fear",
    "gratitude",
    "grief",
    "joy",
    "love",
    "nervousness",
    "optimism",
    "pride",
    "realization",
    "relief",
    "remorse",
    "sadness",
    "surprise",

    # Custom
    "anxiety",
    "anticipation",
    "awe",
    "boredom",
    "contempt",
    "contentment",
    "compassion",
    "despair",
    "ecstasy",
    "envy",
    "frustration",
    "guilt",
    "happiness",
    "hate",
    "hope",
    "humiliation",
    #"hurt",  # Possibly too broad
    "jealousy",
    "loneliness",
    "nostalgia",
    "panic",
    "pity",
    "rage",
    "regret",
    "resentment",
    "shame",
    "sympathy",
    "trust",
]

intention = [
    "speaker agrees",
    "speaker apologizes",
    "speaker commands",
    "speaker complains",
    "speaker disagrees",
    "speaker expresses concern",
    "speaker expresses emotion",
    "speaker gives compliment",
    "speaker gives criticism",
    #"speaker greets",
    "speaker inquires",
    "speaker insults",
    "speaker makes recommendation",
    "speaker seeks assistance",
    "speaker seeks compliment",
    "speaker seeks criticism",
    "speaker seeks emotional reaction",
]
