
# TODO: what about directionality?
emotions = [
    # Labels from google-research-datasets/go_emotions, minus "neutral"
    "admiration",
    "amusement",
    "anger",
    "annoyance",
    "approval",
    "caring",
    "confusion",
    "curiosity",
    "desire",
    "disappointment",
    "disapproval",
    "disgust",
    "embarrassment",
    "excitement",
    "fear",
    "gratitude",
    "grief",
    "joy",
    "love",
    "nervousness",
    "optimism",
    "pride",
    "realization",
    "relief",
    "remorse",
    "sadness",
    "surprise",

    # Custom
    "anxiety",
    "anticipation",
    "awe",
    "boredom",
    "contempt",
    "contentment",
    "compassion",
    "despair",
    "ecstasy",
    "envy",
    "frustration",
    "guilt",
    "happiness",
    "hate",
    "hope",
    "humiliation",
    #"hurt",  # Possibly too broad
    "jealousy",
    "loneliness",
    "nostalgia",
    "panic",
    "pity",
    "rage",
    "regret",
    "resentment",
    "shame",
    "sympathy",
    "trust",
]